# Generated by Django 2.0.6 on 2018-06-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, null=True)),
                ('author', models.CharField(default='LL', max_length=255, null=True)),
                ('tags', models.CharField(max_length=255, null=True)),
                ('brief', models.CharField(max_length=255, null=True)),
                ('content', models.TextField(null=True)),
                ('view_count', models.IntegerField(default=0, null=True)),
                ('comment_count', models.IntegerField(default=0, null=True)),
                ('create_date', models.BigIntegerField(default=1530194226.9338915, null=True)),
                ('publish_date', models.BigIntegerField(default=1530194226.9338915, null=True)),
            ],
            options={
                'db_table': 't_article',
            },
        ),
    ]
