# Generated by Django 2.0.6 on 2018-06-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20180629_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=255, null=True)),
                ('month', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(db_index=True, max_length=255, null=True)),
                ('author', models.CharField(default='LL', max_length=255, null=True)),
                ('tags', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 't_archives',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='create_date',
            field=models.BigIntegerField(default=1530335444.3152902, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.BigIntegerField(default=1530335444.3152902, null=True),
        ),
    ]
